### ISSUE TITLE
What is the difference between SF model and TE model?

### ISSUE THREAD

**Issue by ttgump** [AllenInstitute/coupledAE#1]
Hi,
What is the difference between SF model and TE model of the python codes? Is that possible to provide a tutorial for how to use the coupling autoencoder for my custom data? Thanks.
Best,
Tian Tian

**Comment by rhngla** [comment]
Hi Tian Tian - `SF_model.py` was used for experiments with a synthetic dataset relating to discovery of cell types, and `TE_model.py` was used for the patchseq dataset experiments described in the paper. The architecture of the individual agents in the coupled autoencoder should be designed for custom data you have; the main component you want to re-use from these models is the coupling loss function. Will put up a short tutorial at some point in the future, but in the meanwhile happy to help you out over email.

Cheers,
Rohan
